import { User } from "@/types/user";

export const mockUsers: User[] = [
  {
    id: "currentUser",
    fullName: "You",
    email: "you@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=you",
  },
  {
    id: "1",
    fullName: "Sarah Chen",
    email: "sarah.chen@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=sarah",
  },
  {
    id: "2",
    fullName: "Alex Stanescu",
    email: "alex.stanescu@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=alex",
  },
  {
    id: "3",
    fullName: "Maddie Anita",
    email: "maddie.anita@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=maddie",
  },
  {
    id: "4",
    fullName: "Jordan Lee",
    email: "jordan.lee@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=jordan",
  },
  {
    id: "5",
    fullName: "Project Coordinator",
    email: "coordinator@university.edu",
    password: "password123",
    role: "professor",
  },
  {
    id: "6",
    fullName: "Elena Popescu",
    email: "elena.popescu@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=elena",
  },
  {
    id: "7",
    fullName: "Mihai Ionescu",
    email: "mihai.ionescu@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=mihai",
  },
  {
    id: "8",
    fullName: "Priya Sharma",
    email: "priya.sharma@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=priya",
  },
  {
    id: "9",
    fullName: "David Kim",
    email: "david.kim@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=david",
  },
  {
    id: "10",
    fullName: "Maria Garcia",
    email: "maria.garcia@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=maria",
  },
  {
    id: "11",
    fullName: "Prof. Andrei Dumitrescu",
    email: "andrei.dumitrescu@university.edu",
    password: "password123",
    role: "professor",
    avatar: "https://i.pravatar.cc/150?u=andrei",
  },
  {
    id: "12",
    fullName: "Prof. Laura Marinescu",
    email: "laura.marinescu@university.edu",
    password: "password123",
    role: "professor",
    avatar: "https://i.pravatar.cc/150?u=laura",
  },
  {
    id: "13",
    fullName: "x x",
    email: "x",
    password: "y",
    role: "professor",
    avatar: "https://i.pravatar.cc/150?u=laura",
  },
  {
    id: "14",
    fullName: "a b",
    email: "a",
    password: "b",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=laura",
  },
  {
    id: "15",
    fullName: "Prof. Thomas Wright",
    email: "thomas.wright@university.edu",
    password: "password123",
    role: "professor",
    avatar: "https://i.pravatar.cc/150?u=thomas",
  },
  {
    id: "16",
    fullName: "Dr. Emily Chen",
    email: "emily.chen@university.edu",
    password: "password123",
    role: "professor",
    avatar: "https://i.pravatar.cc/150?u=emily",
  },
  {
    id: "17",
    fullName: "Lucas Miller",
    email: "lucas.miller@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=lucas",
  },
  {
    id: "18",
    fullName: "Sophie Bennett",
    email: "sophie.bennett@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=sophie",
  },
  {
    id: "19",
    fullName: "Wei Zhang",
    email: "wei.zhang@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=wei",
  },
  {
    id: "20",
    fullName: "Isabella Santos",
    email: "isabella.santos@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=isabella",
  },
  {
    id: "21",
    fullName: "Liam O'Connor",
    email: "liam.oconnor@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=liam",
  },
  {
    id: "22",
    fullName: "Prof. Alan Turing",
    email: "alan.turing@university.edu",
    password: "password123",
    role: "professor",
    avatar: "https://i.pravatar.cc/150?u=alan",
  },
  {
    id: "23",
    fullName: "Emma Davis",
    email: "emma.davis@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=emma",
  },
  {
    id: "24",
    fullName: "Noah Wilson",
    email: "noah.wilson@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=noah",
  },
  {
    id: "25",
    fullName: "Mia Taylor",
    email: "mia.taylor@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=mia",
  },
  {
    id: "26",
    fullName: "Ethan Anderson",
    email: "ethan.anderson@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=ethan",
  },
  {
    id: "27",
    fullName: "Ava Thomas",
    email: "ava.thomas@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=ava",
  },
  {
    id: "28",
    fullName: "Dr. Maria Rossi",
    email: "maria.rossi@university.edu",
    password: "password123",
    role: "professor",
    avatar: "https://i.pravatar.cc/150?u=mariar",
  },
  {
    id: "29",
    fullName: "Oliver Jackson",
    email: "oliver.jackson@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=oliver",
  },
  {
    id: "30",
    fullName: "Charlotte White",
    email: "charlotte.white@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=charlotte",
  },
  {
    id: "31",
    fullName: "Elijah Harris",
    email: "elijah.harris@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=elijah",
  },
  {
    id: "32",
    fullName: "Amelia Martin",
    email: "amelia.martin@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=amelia",
  },
  {
    id: "33",
    fullName: "William Thompson",
    email: "william.thompson@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=william",
  },
  {
    id: "34",
    fullName: "Prof. James Holden",
    email: "james.holden@university.edu",
    password: "password123",
    role: "professor",
    avatar: "https://i.pravatar.cc/150?u=jamesh",
  },
  {
    id: "35",
    fullName: "Harper Garcia",
    email: "harper.garcia@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=harper",
  },
  {
    id: "36",
    fullName: "James Martinez",
    email: "james.martinez@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=jamesm",
  },
  {
    id: "37",
    fullName: "Evelyn Robinson",
    email: "evelyn.robinson@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=evelyn",
  },
  {
    id: "38",
    fullName: "Benjamin Clark",
    email: "benjamin.clark@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=benjamin",
  },
  {
    id: "39",
    fullName: "Abigail Rodriguez",
    email: "abigail.rodriguez@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=abigail",
  },
  {
    id: "40",
    fullName: "Henry Lewis",
    email: "henry.lewis@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=henry",
  },
  {
    id: "41",
    fullName: "Emily Lee",
    email: "emily.lee@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=emilyl",
  },
  {
    id: "42",
    fullName: "Alexander Walker",
    email: "alexander.walker@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=alexander",
  },
  {
    id: "43",
    fullName: "Elizabeth Hall",
    email: "elizabeth.hall@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=elizabeth",
  },
  {
    id: "44",
    fullName: "Sebastian Allen",
    email: "sebastian.allen@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=sebastian",
  }
];
