import { User } from "@/types/user";

export const mockUsers: User[] = [
  {
    id: "currentUser",
    fullName: "You",
    email: "you@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=you",
  },
  {
    id: "1",
    fullName: "Sarah Chen",
    email: "sarah.chen@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=sarah",
  },
  {
    id: "2",
    fullName: "Alex Stanescu",
    email: "alex.stanescu@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=alex",
  },
  {
    id: "3",
    fullName: "Maddie Anita",
    email: "maddie.anita@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=maddie",
  },
  {
    id: "4",
    fullName: "Jordan Lee",
    email: "jordan.lee@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=jordan",
  },
  {
    id: "5",
    fullName: "Project Coordinator",
    email: "coordinator@university.edu",
    password: "password123",
    role: "professor",
  },
  {
    id: "6",
    fullName: "Elena Popescu",
    email: "elena.popescu@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=elena",
  },
  {
    id: "7",
    fullName: "Mihai Ionescu",
    email: "mihai.ionescu@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=mihai",
  },
  {
    id: "8",
    fullName: "Priya Sharma",
    email: "priya.sharma@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=priya",
  },
  {
    id: "9",
    fullName: "David Kim",
    email: "david.kim@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=david",
  },
  {
    id: "10",
    fullName: "Maria Garcia",
    email: "maria.garcia@university.edu",
    password: "password123",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=maria",
  },
  {
    id: "11",
    fullName: "Prof. Andrei Dumitrescu",
    email: "andrei.dumitrescu@university.edu",
    password: "password123",
    role: "professor",
    avatar: "https://i.pravatar.cc/150?u=andrei",
  },
  {
    id: "12",
    fullName: "Prof. Laura Marinescu",
    email: "laura.marinescu@university.edu",
    password: "password123",
    role: "professor",
    avatar: "https://i.pravatar.cc/150?u=laura",
  },
  {
    id: "13",
    fullName: "x x",
    email: "x",
    password: "y",
    role: "professor",
    avatar: "https://i.pravatar.cc/150?u=laura",
  },
  {
    id: "14",
    fullName: "a b",
    email: "a",
    password: "b",
    role: "student",
    avatar: "https://i.pravatar.cc/150?u=laura",
  },
];
