import { Project } from '@/types/project';

export const mockProjects: Project[] = [
  { name: 'Mobile App Redesign', client: 'TechCorp', date: 'Mar 2026', rating: 5 },
  { name: 'Component Library', client: 'StartupXYZ', date: 'Feb 2026', rating: 4.9 },
  { name: 'API Gateway', client: 'FinTech Inc', date: 'Mar 2026', rating: 4.7 },
  { name: 'Auth Service', client: 'TechCorp', date: 'Jan 2026', rating: 4.5 },
  { name: 'E-commerce Platform', client: 'ShopNow', date: 'Feb 2026', rating: 3.8 },
  { name: 'Sentiment Analyzer', client: 'MediaCo', date: 'Mar 2026', rating: 4.0 },
  { name: 'Fitness Tracker', client: 'HealthPlus', date: 'Feb 2026', rating: 4.2 },
  { name: 'CRM Migration', client: 'BigCorp', date: 'Jan 2026', rating: 3.9 },
  { name: 'Student Portal', client: 'University', date: 'Mar 2026', rating: 4.1 },
  { name: 'Dashboard Analytics', client: 'DataViz Co', date: 'Apr 2026', rating: 4.6 },
  { name: 'Chat Platform', client: 'SocialNet', date: 'Dec 2025', rating: 4.3 },
  { name: 'Inventory System', client: 'RetailMax', date: 'Nov 2025', rating: 3.7 },
  { name: 'Payment Gateway', client: 'PayFlow', date: 'Jan 2026', rating: 4.8 },
  { name: 'HR Management Tool', client: 'PeopleFirst', date: 'Apr 2026', rating: 4.4 },
  { name: 'IoT Dashboard', client: 'SmartHome Inc', date: 'Mar 2026', rating: 4.0 },
  { name: 'Learning Platform', client: 'EduTech', date: 'Feb 2026', rating: 4.5 },
  { name: 'Recipe App', client: 'FoodieHub', date: 'Dec 2025', rating: 3.6 },
  { name: 'Event Planner', client: 'EventBright', date: 'Jan 2026', rating: 4.1 },
  { name: 'Portfolio Builder', client: 'CreativeStudio', date: 'Apr 2026', rating: 4.7 },
  { name: 'Weather App', client: 'ClimateTech', date: 'Nov 2025', rating: 3.9 },
  { name: 'Task Manager', client: 'ProductivityCo', date: 'May 2026', rating: 4.3 },
  { name: 'Video Streaming Service', client: 'StreamNow', date: 'Apr 2026', rating: 4.6 },
  { name: 'Real Estate Finder', client: 'HomeFinder', date: 'Mar 2026', rating: 3.8 },
  { name: 'Social Media Dashboard', client: 'BuzzMetrics', date: 'Feb 2026', rating: 4.2 },
  { name: 'Supply Chain Tracker', client: 'LogiTrack', date: 'Jan 2026', rating: 4.0 },
  { name: 'Music Recommendation Engine', client: 'TuneWave', date: 'Dec 2025', rating: 4.4 },
  { name: 'Expense Tracker', client: 'BudgetWise', date: 'May 2026', rating: 4.1 },
  { name: 'Online Booking System', client: 'BookItNow', date: 'Apr 2026', rating: 4.5 },
  { name: 'Language Learning App', client: 'LingoLeap', date: 'Mar 2026', rating: 4.7 },
  { name: 'Customer Support Bot', client: 'HelpDesk AI', date: 'Feb 2026', rating: 3.5 },
  { name: 'Fleet Management', client: 'DriveFleet', date: 'Jan 2026', rating: 3.9 },
  { name: 'Parking Spot Finder', client: 'ParkEasy', date: 'Nov 2025', rating: 3.4 },
  { name: 'Digital Menu', client: 'FoodieHub', date: 'May 2026', rating: 4.8 },
  { name: 'Code Review Tool', client: 'DevTools Inc', date: 'Apr 2026', rating: 4.6 },
  { name: 'Newsletter Platform', client: 'MailCraft', date: 'Mar 2026', rating: 4.0 },
  { name: 'Volunteer Matching', client: 'GiveBack', date: 'Feb 2026', rating: 4.3 },
  { name: 'Campus Navigation', client: 'University', date: 'Jan 2026', rating: 3.7 },
  { name: 'Pet Adoption Platform', client: 'PawFriends', date: 'Dec 2025', rating: 4.9 },
];
