import { Project } from '@/types/project';

export const mockProjects: Project[] = [
  { name: 'Mobile App Redesign', client: 'TechCorp', date: 'Mar 2026', rating: 5 },
  { name: 'Component Library', client: 'StartupXYZ', date: 'Feb 2026', rating: 4.9 },
  { name: 'API Gateway', client: 'FinTech Inc', date: 'Mar 2026', rating: 4.7 },
  { name: 'Auth Service', client: 'TechCorp', date: 'Jan 2026', rating: 4.5 },
  { name: 'E-commerce Platform', client: 'ShopNow', date: 'Feb 2026', rating: 3.8 },
  { name: 'Sentiment Analyzer', client: 'MediaCo', date: 'Mar 2026', rating: 4.0 },
  { name: 'Fitness Tracker', client: 'HealthPlus', date: 'Feb 2026', rating: 4.2 },
  { name: 'CRM Migration', client: 'BigCorp', date: 'Jan 2026', rating: 3.9 },
  { name: 'Student Portal', client: 'University', date: 'Mar 2026', rating: 4.1 },
  { name: 'Dashboard Analytics', client: 'DataViz Co', date: 'Apr 2026', rating: 4.6 },
  { name: 'Chat Platform', client: 'SocialNet', date: 'Dec 2025', rating: 4.3 },
  { name: 'Inventory System', client: 'RetailMax', date: 'Nov 2025', rating: 3.7 },
  { name: 'Payment Gateway', client: 'PayFlow', date: 'Jan 2026', rating: 4.8 },
  { name: 'HR Management Tool', client: 'PeopleFirst', date: 'Apr 2026', rating: 4.4 },
  { name: 'IoT Dashboard', client: 'SmartHome Inc', date: 'Mar 2026', rating: 4.0 },
  { name: 'Learning Platform', client: 'EduTech', date: 'Feb 2026', rating: 4.5 },
  { name: 'Recipe App', client: 'FoodieHub', date: 'Dec 2025', rating: 3.6 },
  { name: 'Event Planner', client: 'EventBright', date: 'Jan 2026', rating: 4.1 },
  { name: 'Portfolio Builder', client: 'CreativeStudio', date: 'Apr 2026', rating: 4.7 },
  { name: 'Weather App', client: 'ClimateTech', date: 'Nov 2025', rating: 3.9 },
  { name: 'Task Manager', client: 'ProductivityCo', date: 'May 2026', rating: 4.3 },
  { name: 'Video Streaming Service', client: 'StreamNow', date: 'Apr 2026', rating: 4.6 },
  { name: 'Real Estate Finder', client: 'HomeFinder', date: 'Mar 2026', rating: 3.8 },
  { name: 'Social Media Dashboard', client: 'BuzzMetrics', date: 'Feb 2026', rating: 4.2 },
  { name: 'Supply Chain Tracker', client: 'LogiTrack', date: 'Jan 2026', rating: 4.0 },
  { name: 'Music Recommendation Engine', client: 'TuneWave', date: 'Dec 2025', rating: 4.4 },
  { name: 'Expense Tracker', client: 'BudgetWise', date: 'May 2026', rating: 4.1 },
  { name: 'Online Booking System', client: 'BookItNow', date: 'Apr 2026', rating: 4.5 },
  { name: 'Language Learning App', client: 'LingoLeap', date: 'Mar 2026', rating: 4.7 },
  { name: 'Customer Support Bot', client: 'HelpDesk AI', date: 'Feb 2026', rating: 3.5 },
  { name: 'Fleet Management', client: 'DriveFleet', date: 'Jan 2026', rating: 3.9 },
  { name: 'Parking Spot Finder', client: 'ParkEasy', date: 'Nov 2025', rating: 3.4 },
  { name: 'Digital Menu', client: 'FoodieHub', date: 'May 2026', rating: 4.8 },
  { name: 'Code Review Tool', client: 'DevTools Inc', date: 'Apr 2026', rating: 4.6 },
  { name: 'Newsletter Platform', client: 'MailCraft', date: 'Mar 2026', rating: 4.0 },
  { name: 'Volunteer Matching', client: 'GiveBack', date: 'Feb 2026', rating: 4.3 },
  { name: 'Campus Navigation', client: 'University', date: 'Jan 2026', rating: 3.7 },
  { name: 'Pet Adoption Platform', client: 'PawFriends', date: 'Dec 2025', rating: 4.9 },
  { name: 'GraphQL API Migration', client: 'DataStream', date: 'May 2026', rating: 4.6 },
  { name: 'Automated E2E Test Suite', client: 'QA Labs', date: 'Apr 2026', rating: 4.8 },
  { name: 'Fraud Detection Pipeline', client: 'SecureBank', date: 'Jun 2026', rating: 4.9 },
  { name: 'Kubernetes Cluster Setup', client: 'CloudScale', date: 'Feb 2026', rating: 4.5 },
  { name: 'Web Accessibility Overhaul', client: 'GovTech', date: 'Jan 2026', rating: 5.0 },
  { name: 'Image Recognition Service', client: 'VisionAI', date: 'Mar 2026', rating: 4.2 },
  { name: 'Load Balancer Configuration', client: 'HighTraffic Inc', date: 'May 2026', rating: 4.7 },
  { name: 'AR Furniture Viewer', client: 'HomeDecor', date: 'Jun 2026', rating: 4.4 },
  { name: 'Chaos Testing Bot', client: 'Resilience Corp', date: 'Dec 2025', rating: 3.9 },
  { name: 'Serverless Payment Webhook', client: 'PayFlow', date: 'Apr 2026', rating: 4.8 },
  { name: 'Zero Trust Security Model', client: 'DefendIt', date: 'May 2026', rating: 5.0 },
  { name: 'Predictive Text Algorithm', client: 'TypeFast', date: 'Feb 2026', rating: 4.1 },
  { name: 'Real-time Log Analytics', client: 'MetricsPro', date: 'Mar 2026', rating: 4.3 },
  { name: 'Dark Mode Design System', client: 'StyleUX', date: 'Jan 2026', rating: 4.9 },
  { name: 'iOS Home Screen Widgets', client: 'AppMasters', date: 'May 2026', rating: 4.6 },
  { name: 'Voice Assistant Integration', client: 'SmartHome Inc', date: 'Jun 2026', rating: 3.8 },
  { name: 'Automated Dependency Updates', client: 'DevTools Inc', date: 'Feb 2026', rating: 4.5 },
  { name: 'Micro Frontends Architecture', client: 'BigStore', date: 'Apr 2026', rating: 4.2 },
  { name: 'ETL Data Pipeline Upgrade', client: 'DataWorks', date: 'Mar 2026', rating: 4.7 },
  { name: 'Distributed Caching Layer', client: 'SpeedyNet', date: 'Dec 2025', rating: 4.4 },
  { name: 'PWA Offline Mode', client: 'NewsNow', date: 'Jan 2026', rating: 4.0 },
  { name: 'Biometric Auth Module', client: 'SecureBank', date: 'May 2026', rating: 4.9 },
  { name: 'NLP Chatbot Enhancements', client: 'HelpDesk AI', date: 'Apr 2026', rating: 3.7 },
  { name: 'API Rate Limiting Service', client: 'CloudScale', date: 'Jun 2026', rating: 4.8 },
  { name: 'User Session Replay Tool', client: 'UX Analytics', date: 'Mar 2026', rating: 4.6 },
  { name: 'Blockchain Smart Contract', client: 'CryptoFin', date: 'Feb 2026', rating: 3.5 },
  { name: 'Video Encoding Microservice', client: 'StreamNow', date: 'May 2026', rating: 4.3 },
  { name: 'Drone Fleet Routing Algorithm', client: 'LogiTrack', date: 'Jan 2026', rating: 4.7 },
  { name: '3D WebGL Product Configurator', client: 'AutoMaker', date: 'Apr 2026', rating: 4.9 },
  { name: 'Disaster Recovery Simulation', client: 'SafeGuard', date: 'Jun 2026', rating: 4.5 }
];
