import { Achievement } from '@/types/achievement';

export const mockAchievements: Achievement[] = [
  { title: 'Fast Delivery Award', description: '5 projects ahead of schedule' },
  { title: 'Top Rated Team', description: '4.8+ rating for 6 months' },
  { title: 'Zero Downtime', description: '99.9% uptime for 12 months' },
  { title: 'Security Champion', description: 'Passed all security audits' },
  { title: 'Hackathon Winners', description: '1st place Spring 2026' },
  { title: 'Innovation Award', description: 'Best ML model accuracy' },
  { title: 'App Store Featured', description: 'Featured app in Q1 2026' },
  { title: 'Migration Master', description: '3 legacy systems modernized' },
  { title: 'Code Quality Star', description: '95%+ test coverage' },
  { title: 'Mentorship Excellence', description: 'Mentored 10+ junior members' },
  { title: 'Open Source Contributor', description: '50+ merged PRs in open source' },
  { title: 'Bug Bounty Hunter', description: 'Found and fixed 100+ critical bugs' },
  { title: 'Client Favorite', description: '5 consecutive 5-star client reviews' },
  { title: 'Sprint Champion', description: '10 sprints completed with 100% velocity' },
  { title: 'Community Builder', description: 'Organized 5+ tech meetups' },
  { title: 'First Commit', description: 'Made the very first commit in the repo' },
  { title: 'Documentation Hero', description: 'Wrote docs for 20+ endpoints' },
  { title: 'CI/CD Pioneer', description: 'Set up the first CI/CD pipeline' },
  { title: 'Pair Programming Pro', description: '50+ pair programming sessions' },
  { title: 'Cross-Team Collaborator', description: 'Contributed to 3+ different teams' },
  { title: 'Performance Optimizer', description: 'Reduced load time by 40%' },
  { title: 'Accessibility Advocate', description: 'Achieved WCAG AA compliance' },
  { title: 'Design System Creator', description: 'Built a reusable component library' },
  { title: 'Code Review Legend', description: '200+ code reviews completed' },
  { title: 'On-Time Delivery', description: 'Never missed a deadline in 6 months' },
  { title: 'Research Pioneer', description: 'Published 3 internal tech papers' },
  { title: 'Quick Learner', description: 'Picked up a new tech stack in under 2 weeks' },
  { title: 'Team Spirit Award', description: 'Voted most helpful by teammates' },
  { title: 'Demo Day Winner', description: 'Best project presentation of the semester' },
  { title: 'Testing Guru', description: 'Wrote 500+ unit tests' },
  { title: 'Cloud Native', description: 'Successfully migrated backend to serverless architecture' },
  { title: 'Containerization Expert', description: 'Dockerized all microservices for local dev' },
  { title: 'Refactoring Guru', description: 'Reduced overall technical debt by 30%' },
  { title: 'Type Safety Net', description: 'Achieved 100% strict TypeScript compliance' },
  { title: 'Pixel Perfect', description: 'Matched Figma designs with 100% accuracy' },
  { title: 'Animation Wizard', description: 'Implemented complex 60fps UI animations' },
  { title: 'Database Optimizer', description: 'Reduced complex query times by over 50%' },
  { title: 'API Architect', description: 'Designed scalable RESTful APIs for 3 platforms' },
  { title: 'Agile Evangelist', description: 'Maintained perfect Jira/Trello boards for 5 sprints' },
  { title: 'Bug Squasher', description: 'Resolved 50+ user-reported issues in record time' },
  { title: 'Feature Factory', description: 'Delivered 20+ epic features in a single quarter' },
  { title: 'High Traffic Hero', description: 'Handled 10k+ concurrent users without crashing' },
  { title: 'Early Bird', description: 'Merged a critical PR before 6:00 AM' },
  { title: 'Night Owl', description: 'Pushed a life-saving hotfix at 2:00 AM' },
  { title: 'Coffee Powered', description: 'Recorded the most commits during a weekend hackathon' },
  { title: 'Stack Overflow Survivor', description: 'Solved a critical bug with zero external documentation' },
  { title: 'Internal Tooling Hero', description: 'Created a library adopted by 5 other teams' },
  { title: 'Localization Master', description: 'Translated the platform into 3 new languages' },
  { title: 'Green Energy Coder', description: 'Optimized app to reduce battery consumption by 20%' },
  { title: 'Launch Day Legend', description: 'Led the successful V1.0 production release' },
];
